version: '3'
services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile.php-apache
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./app:/var/www/html
      - ./conf/apache.conf:/etc/apache2/sites-available/000-default.conf

  mariadb:
    image: 'mariadb:latest'
    volumes:
      - './database:/var/lib/mysql'
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}

    networks:
      - laravel-network
      
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
        - ${PMA_PORT}:80
      environment:
        #- PMA_ARBITRARY=1
        PMA_HOST: mariadb
        PMA_USER: ${MARIADB_USER}
        PMA_PASSWORD: ${MARIADB_PASSWORD}
      networks:
        - laravel-network

networks:
  laravel-network:
    driver: bridge
